### ISSUE TITLE
(load "/dev/urandom") returns confusing error

### ISSUE THREAD

**Issue by arwn** [geostran/risp#5]
`(load "/dev/urandom")` -> `(Err: expected (Str), received (Str))`

**Comment by geostran** [comment]
The error message is completely wrong! It should be `(Err: expected (Sym), received (Str))`
When loading a module, a symbol is passed instead of a string, so the proper use would be:
`(load /dev/urandom)`
Let me fix the error message.

**Comment by geostran** [comment]
fixed!
